apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: ghcr.io/vsevolod-rusinskiy/newartspace-admin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4173
          command: ["./node_modules/.bin/http-server", "./dist", "-p", "4173"]
          env:
            - name: VITE_APP_PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: admin-config
                  key: VITE_APP_PROTOCOL
            - name: VITE_APP_HOST
              valueFrom:
                configMapKeyRef:
                  name: admin-config
                  key: VITE_APP_HOST
            - name: VITE_APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: admin-config
                  key: VITE_APP_PORT
            - name: VITE_APP_API_URL
              valueFrom:
                configMapKeyRef:
                  name: admin-config
                  key: VITE_APP_API_URL
      imagePullSecrets:
        - name: ghcr-io-secret
