apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: admin-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: admin
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
