name: Master CI/CD

on:
  push:
    branches:
      - master

jobs:
  prettier-lint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run Prettier check
        run: yarn prettier-check

      - name: Run Lint check
        run: yarn lint

  build-and-push-image:
    needs: prettier-lint-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      # Сборка и загрузка Docker образа в GitHub Packages
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/vsevolod-rusinskiy/newartspace-admin:latest
          no-cache: true
          buildx: true

  deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 360m
          script: |
            cd /var/www/newartspace/admin
            git restore .
            git pull origin master

      - name: Stop and remove existing container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 360m
          script: |
            if [ $(docker ps -q -f name=admin) ]; then
              echo "Stopping existing container..."
              docker stop admin
              while [ $(docker ps -q -f name=admin) ]; do
                sleep 1
              done
            fi

            if [ $(docker ps -aq -f status=exited -f name=admin) ]; then
              echo "Removing existing container..."
              docker rm admin
              while [ $(docker ps -aq -f name=admin) ]; do
                sleep 1
              done
            fi

      - name: Run new container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 360m
          script: |
            echo "Switching to application directory..."
            cd /var/www/newartspace/admin

            echo "Running the application container..."
            docker run --env-file .env -d --name admin --restart unless-stopped -p 3002:4173 ghcr.io/vsevolod-rusinskiy/newartspace-admin:latest
